[package]
name = "wasm-ed25519ph"
version = "0.1.0"
authors = ["fran <fran.sl@atlascity.io>", "nshcore <nshcore@protonmail.com>", "Richard Littauer <richard+github@burntfen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasm-bindgen = "0.2"
catalyst-common = { git = "https://github.com/catalyst-network/Catalyst-rs", branch = "develop"}
console_error_panic_hook = "0.1.6"
wee_alloc = "0.4.5"
wasm-bindgen-test = "0.3.4"
rand = { version = "0.7.3", features = ["wasm-bindgen"]}

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[lib]
crate-type = ["cdylib"]
